# -*- coding: utf-8 -*-
"""Project2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BlziTap_GjfgVbDTI6i7t4UYPUNZF7YS
"""

# Prompt the user to enter the number of hours worked
hours = float(input("Enter Hours: "))

# Prompt the user to enter their rate per hour
rate = float(input("Enter Rate: "))

# Calculate the gross pay
pay = hours * rate

# Print the gross pay
print("Pay:", pay)

